### ISSUE TITLE
Update major road feature OSM tags

### ISSUE THREAD

**Issue by dfsnow** [ccao-data/data-architecture#195]
Currently, the `major_road` feature is constructed by querying line shapefiles from OpenStreetMap. The current query uses only three tags `highway/motorway`, `highway/primary`, and `highway/trunk`.

There are two issues with this:

1. OSM tags are inconsistent, even within Cook County. Often things that most people would consider major roads are not tagged as such.
2. There are a variety of link tag types that we should probably include in this road definition, e.g. `highway/primary_link`

As such, we should update the [loader script](https://github.com/ccao-data/data-architecture/blob/master/aws-s3/scripts-ccao-data-warehouse-us-east-1/spatial-environment-major_road.R) and rebuild the feature using the expanded tag set.

**Comment by dfsnow** [comment]
Pinging @ccao-jardine on this since I know there's interest from other departments as well.

**Comment by ccao-jardine** [comment]
Ha, great minds think alike! I have a related issue drafted up that we'll discuss today.

**Comment by wagnerlmichael** [comment]
It turns out these tags may have been more consistent than originally thought. It could be that they updated their data. I looked at the[ tags at OSM](https://wiki.openstreetmap.org/wiki/Map_features#Highway), and it didn't seem like there were a lot of solid options for potential additions. 

We did try including the `links` tags for `motorway`,  `primary`, and `trunk` roads, but it changed very little, as shown below

![existing_main_roads](https://github.com/ccao-data/data-architecture/assets/93889413/dfc352f0-af7b-4706-ae70-2a555409f4d8)

![existing_primary_motor_trunk_links](https://github.com/ccao-data/data-architecture/assets/93889413/f6ef570d-2ef8-4987-8c70-3cd8e6e72050)

We will close the issue and re-run the script, in case they did update their data.
