### ISSUE TITLE
Check use cases for `dbt-athena` Python support

### ISSUE THREAD

**Issue by dfsnow** [ccao-data/data-architecture#388]
We may be able to:

- [x] Move some of the ingest queries / raw processing directly to dbt
- [x] Move the res ratio stats reporting to dbt

**Comment by jeancochrane** [comment]
I'm going to keep some running notes here as I investigate:

* Python models won't work for ingest scripts that access data from a local drive, e.g. [`spatial.school`](https://github.com/ccao-data/data-architecture/blob/c7ebc9d850dcdb005f702290ccc3bce855cf8a31/aws-s3/scripts-ccao-data-raw-us-east-1/spatial-school.R#L258-L272). We might be able to factor out additional extraction scripts that are intended to run locally prior to the model running, but that will increase complexity of the pipeline.

**Comment by jeancochrane** [comment]
@dfsnow After some investigation, my expectation is that Python models will only have limited utility for our ingests and transformations. Python models via PySpark are still very experimental (there have been no new releases since the release that added preliminary support for it in Feburary) and Athena PySpark has two limitations that are currently deal killers for many of our most complex ingest/transformation scripts:

* Limited support for external libraries that aren't [built-in](https://docs.aws.amazon.com/athena/latest/ug/notebooks-spark-preinstalled-python-libraries.html) (external libraries must be stored on S3 in order to be accessible)
* No ability to access data or connect to databases that are stored locally or on private network drives

Still, I think there are _some_ **ingest** scripts that could be refactored to use Python models, particularly ones that read data from public URLs and perform limited transformations on them (e.g. `housing.ihs_index` and `sale.mydec`). I propose we pull out the easiest of these, try them out with Python models, and use that as a spike to test the stability of the approach. In my estimation, that would be these scripts:

* `housing.ihs_index` (reads files from [remote URL](https://github.com/ccao-data/data-architecture/blob/c7ebc9d850dcdb005f702290ccc3bce855cf8a31/aws-s3/scripts-ccao-data-raw-us-east-1/housing-ihs_index.R#L17-L22))
* `sale.mydec` (reads files from [remote URL](https://github.com/ccao-data/data-architecture/blob/c7ebc9d850dcdb005f702290ccc3bce855cf8a31/aws-s3/scripts-ccao-data-raw-us-east-1/sale-mydec.R#L16-L22))
*  `schools.great_schools_rating` (reads files from [remote URL](https://github.com/ccao-data/data-architecture/blob/c7ebc9d850dcdb005f702290ccc3bce855cf8a31/aws-s3/scripts-ccao-data-raw-us-east-1/school-great_schools_rating.R#L24-L31))
* `spatial.access` (reads files from [remote URL](https://github.com/ccao-data/data-architecture/blob/c7ebc9d850dcdb005f702290ccc3bce855cf8a31/aws-s3/scripts-ccao-data-raw-us-east-1/spatial-access.R#L13-L29))
* `spatial.midway_noise_monitor` ([reads files from remote URL](https://github.com/ccao-data/data-architecture/blob/c7ebc9d850dcdb005f702290ccc3bce855cf8a31/aws-s3/scripts-ccao-data-raw-us-east-1/spatial-environment-midway_noise_monitor.R#L14-L30))
* `spatial.police` ([reads data from the City open data portal](https://github.com/ccao-data/data-architecture/blob/c7ebc9d850dcdb005f702290ccc3bce855cf8a31/aws-s3/scripts-ccao-data-raw-us-east-1/spatial-police.R#L11-L25))
* `spatial.transit` ([reads data from remote URLs](https://github.com/ccao-data/data-architecture/blob/c7ebc9d850dcdb005f702290ccc3bce855cf8a31/aws-s3/scripts-ccao-data-raw-us-east-1/spatial-transit.R#L29-L32))

On the **transformation** front, I think we should continue to focus on refactoring transformations to SQL where possible (https://github.com/ccao-data/data-architecture/issues/99), which is tractable and involves a well-supported dbt approach (SQL models). I expect that in the process of doing so, we'll also end up identifying transformations that would be good candidates for Python (i.e. transformations that don't work well in SQL but are simple enough to work in Python without needing external libraries), and our work on the ingest front will help us determine how viable those transformations would be as Python models.

**Comment by jeancochrane** [comment]
Superseded by #393, #394, and #99.
